QA SP update 1
Shift3/standards-and-practices pull request #228
Opened 2020-12-15 20:09 UTC by dcedano

## Changes
_List Changes Introduced by this PR_
1. Is Report of Issues required?
2. Post Sprint Meeting
2a. Closing Milestones
2b. Certificate of Completion 
3. QA will set up Project Board
4. Copying previous acceptance test for new sprint
5. Requesting a New Sprint

## Purpose
_We have already started to use some of these new standards during our QA sprint process. These new standards have helped QA to be more organized as well as giving PM's and devs a better understanding of where testing is during a sprint. This is not the final version of this document. I will be adding necessary links and descriptions after break._

## Approach
_Optional Post Sprint Meeting gives developers a chance to ask about issues that have been posted before a sprint has officially ended. PM's in need of a Report of Issues can now request that in a  way that keeps QA standards. Projects Managers will be notified when a sprint is officially over via email._

2020-12-15 20:17 UTC, michaelachrisco requested changes
Thanks for the updated PR @dcedano 

Can you please create an issue and link that issue to this PR?

2020-12-17 18:22 UTC, mwallert reviewed
Changes look good to me! Once this issue is setup this is good to merge imo

2020-12-18 19:25 UTC, dcedano commented
@michaelachrisco @mwallert thanks guys! I hope I did this right but let me know otherwise 😅

2021-01-04 19:42 UTC, michaelachrisco commented
> @michaelachrisco @mwallert thanks guys! I hope I did this right but let me know otherwise sweat_smile

the only thing preventing this PR being approved is the lack of a referenced issue. All PRs must have a i[ssue attached](https://github.com/Shift3/standards-and-practices/blob/df73e5c586f9d908d5b0eececec72919faf70a0e/standards/contributing.md) before a PR is approved. Other than that, It looks really good and I would love to have this in the repo.

2021-01-07 16:26 UTC, michaelachrisco commented
Thanks @dcedano  for taking care of the issue. Ill go ahead and merge!

2021-01-07 16:27 UTC, michaelachrisco approved these changes

2021-01-07 16:27 UTC, merged