Helpful Development Plugins - React
Shift3/standards-and-practices pull request #232
Opened 2021-01-07 20:34 UTC by caroham29

## Changes
_List Changes Introduced by this PR_
1. Add to list of safe and helpful development plugins
2. Specific to React

## Purpose
Create a location to share helpful plugins used by our development team. Adding a couple of resources commonly used in React. 

## Approach
This change will give us a centralized location of helpful plugins related to development in React.

- [React Developer Tools](https://github.com/facebook/react/tree/master/packages/react-devtools-extensions)
- [Redux DevTools](https://github.com/zalmoxisus/redux-devtools-extension)

2021-01-07 20:35 UTC, caroham29 commented on best-practices/client-side/framework/react/README.md
> +## Helpful React Development Web Plugins
*Revised* Day 3 Checklist! Here's a couple of helpful React development web plugins. 👍🏾

2021-01-08 16:22 UTC, michaelachrisco requested changes
@caroham29 The only thing preventing this PR being approved is the lack of a referenced issue. All PRs must have an issue attached before a PR is approved.

Basically, just add Closes #999 <-- issue number here
to the end of your current PR and you should be good.

I look forward to having more react based tools in our standards!

2021-01-08 22:41 UTC, codysmith287 approved these changes
Nice addition here! I've used both of these web plugins before and they've been super helpful for debugging!

2021-01-11 17:51 UTC, coreyshuman commented
@caroham29 can you put the `closes #231` into the body of your PR post, instead of the title? GitHub has some automation smarts built in, so if you include that line in the body, it will automatically close the Issue once the PR is merged. It will also create a hyperlink reference between the PR and the Issue.

Check out this recent PR for an example: https://github.com/Shift3/standards-and-practices/pull/228

Here's the GitHub documentation on this feature.
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

2021-01-13 08:43 UTC, caroham29 commented
> @caroham29 can you put the `closes #231` into the body of your PR post, instead of the title? GitHub has some automation smarts built in, so if you include that line in the body, it will automatically close the Issue once the PR is merged. It will also create a hyperlink reference between the PR and the Issue.
> 
> Check out this recent PR for an example: #228
> 
> Here's the GitHub documentation on this feature.
> https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

@coreyshuman Done, and thanks for the documentation link.

2021-01-13 16:19 UTC, michaelachrisco approved these changes
Thanks for the edit. Approved!

2021-01-13 16:19 UTC, merged